# Generated by Django 3.1.7 on 2021-03-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20210330_0729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
