# Generated by Django 3.1.7 on 2021-03-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_auto_20210331_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='intimemodel',
            name='ip',
            field=models.TextField(default=' '),
        ),
    ]
