# Generated by Django 3.1.7 on 2021-03-31 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0010_auto_20210331_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DateOfJoin',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 22, 45, 33, 80749)),
        ),
    ]
