# Generated by Django 3.1.7 on 2021-04-01 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0011_profile_dateofjoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='intimemodel',
            name='City',
            field=models.CharField(default=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DateOfJoin',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 12, 43, 54, 229972)),
        ),
    ]
