# Generated by Django 3.1.7 on 2021-04-02 20:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emp', '0016_auto_20210402_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DateOfJoin',
            field=models.DateField(default=datetime.datetime(2021, 4, 2, 20, 15, 43, 278707)),
        ),
        migrations.CreateModel(
            name='production_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Production_time', models.DateTimeField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
