# Generated by Django 3.1.7 on 2021-04-02 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0017_auto_20210402_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DateOfJoin',
            field=models.DateField(default=datetime.datetime(2021, 4, 2, 20, 17, 8, 942044)),
        ),
    ]
