# Generated by Django 3.1.7 on 2021-04-02 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0018_auto_20210402_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_time',
            name='Production_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DateOfJoin',
            field=models.DateField(default=datetime.datetime(2021, 4, 2, 20, 38, 36, 722288)),
        ),
    ]
