# Generated by Django 3.1.7 on 2021-04-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0019_auto_20210402_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_time',
            name='dateworked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DateOfJoin',
            field=models.DateField(default=None),
        ),
    ]
